import "src/main/DSL/tasks.dsl"
import "src/main/DSL/groups.dsl"
import "src/main/DSL/assignments.dsl"
import "src/main/DSL/checkpoints.dsl"
import "src/main/DSL/settings.dsl"
import "src/main/DSL/build.dsl"